# Generated by Django 5.0.6 on 2024-07-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='total_price',
        ),
    ]
