# Generated by Django 4.2.13 on 2024-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(default='some text...', max_length=256),
        ),
    ]
