# Generated by Django 4.2.13 on 2024-07-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
